class_name UiText
extends RefCounted

# Home scene labels
const HOME_DAILY_TASK := "每日任務"
const HOME_MAIL := "信箱"
const HOME_CHAT := "聊天"
const HOME_BOSS := "挑戰 Boss"
const HOME_IDLE_READY := "清理貓砂盆"
const HOME_IDLE_NOT_READY := "乾淨貓砂盆"

# Home navigation labels
const NAV_SCOOPER := "鏟屎官"
const NAV_CONFIG := "編隊"
const NAV_ENHANCE := "強化"
const NAV_ACTIVITY := "活動"
const NAV_SHOP := "商店"

# Home scoop and idle labels
const HOME_SANDBOX_TITLE := "清理貓砂盆"
const HOME_SANDBOX_TIME_FORMAT := "累積時間：%d 小時 %d 分"
const HOME_SANDBOX_PENDING_POOP := "待鏟屎堆：%d"
const HOME_SANDBOX_CLEAN_NOW := "立即清理"
const HOME_SANDBOX_CLEAN_FAILED := "清理失敗"
const HOME_SANDBOX_NONE_EXTRA := "這次沒有額外獎勵"
const HOME_SANDBOX_GAINED_PREFIX := "獲得："
const HOME_CLAIM_REWARDS := "領取獎勵"
const HOME_CLAIM_FAILED_TITLE := "領取失敗"
const HOME_CLAIM_FAILED_MESSAGE := "放置獎勵領取失敗"
const HOME_IDLE_DIALOG_TITLE := "放置獎勵"
const HOME_MAIL_DIALOG_TITLE := "信箱"
const HOME_CHAT_DIALOG_TITLE := "聊天"
const HOME_SCOOPER_EXP_TITLE := "鏟屎官 EXP"
const HOME_SCOOPER_BUTTON := "清理貓砂"
const HOME_SCOOPER_EMPTY := "目前沒有可清理的貓砂"
const HOME_SCOOPER_ERROR := "清理失敗，請稍後再試"
const HOME_SCOOPER_RESULT_PREFIX := "本次獲得："

# Battle labels
const BATTLE_RESULT_WIN := "勝利"
const BATTLE_RESULT_LOSE := "失敗"

# Reward labels
const REWARD_GOLD := "金幣"
const REWARD_POOP := "屎堆"
const REWARD_CAT_FOOD := "貓糧"
const REWARD_DIAMONDS := "鑽石"
const REWARD_WHISKERS := "鬍鬚"
const REWARD_EXP := "EXP"
const REWARD_MEMORY_SHARDS := "回憶碎片"

# Scooper shell labels
const SCOOPER_PAGE_TITLE := "鏟屎官"
const SCOOPER_BACK := "返回"
const SCOOPER_RESOURCE_FORMAT := "金幣：%d    貓砂：%d    回憶碎片：%d"
const SCOOPER_TAB_EQUIPMENT := "裝備"
const SCOOPER_TAB_ABILITY := "特殊能力"
const SCOOPER_TAB_MEMORY := "回憶"
const SCOOPER_TAB_TREASURE := "寶藏"
const SCOOPER_TAB_ACHIEVEMENT := "成就"
const SCOOPER_DESC_EQUIPMENT := "查看裝備等級、功能與升級狀態，強化鏟屎官的日常效率。"
const SCOOPER_DESC_ABILITY := "整理已擁有的特殊能力效果與來源，快速確認你的被動加成。"
const SCOOPER_DESC_MEMORY := "透過回憶解鎖額外能力，補齊鏟屎官成長路線。"
const SCOOPER_DESC_TREASURE := "檢視已持有寶藏與所有累積加成。"
const SCOOPER_DESC_ACHIEVEMENT := "追蹤成就進度並快速領取可獲得的獎勵。"
const SCOOPER_BADGE_READY := "可領取"

# Scooper equipment labels
const SCOOPER_EQUIPMENT_SUMMARY_FORMAT := "已解鎖 %d/%d"
const SCOOPER_EQUIPMENT_EMPTY := "目前沒有可顯示的裝備"
const SCOOPER_EQUIPMENT_LOADING := "載入中..."
const SCOOPER_EQUIPMENT_LEVEL_FORMAT := "Lv.%d/%d"
const SCOOPER_EQUIPMENT_LEVEL_LINE_FORMAT := "%s Lv %d/%d  EXP %d/%d"
const SCOOPER_EQUIPMENT_LOCKED_PREFIX := "未解鎖"
const SCOOPER_EQUIPMENT_BROKEN_PREFIX := "損壞"
const SCOOPER_EQUIPMENT_SICK_PREFIX := "治療"
const SCOOPER_EQUIPMENT_UNLOCK_AT := "鏟屎官等級達 Lv.%d 解鎖"
const SCOOPER_EQUIPMENT_EXP_FORMAT := "EXP %d/%d"
const SCOOPER_EQUIPMENT_LEVEL_MAX := "已達當前等級上限"
const SCOOPER_EQUIPMENT_PURCHASE := "%d金幣"
const SCOOPER_EQUIPMENT_REPAIR := "修理 %d 金幣"
const SCOOPER_EQUIPMENT_TREAT := "治療 %d 金幣"
const SCOOPER_EQUIPMENT_UPGRADE := "%d金幣"
const SCOOPER_EQUIPMENT_UNLOCK := "%d金幣 解鎖"
const SCOOPER_EQUIPMENT_ACTION_PURCHASE := "購買"
const SCOOPER_EQUIPMENT_ACTION_REPAIR := "修理"
const SCOOPER_EQUIPMENT_ACTION_TREAT := "治療"
const SCOOPER_EQUIPMENT_ACTION_UPGRADE := "升級"
const SCOOPER_EQUIPMENT_ACTION_FAILED := "%s失敗"
const SCOOPER_EQUIPMENT_ACTION_FAILED_DEFAULT := "操作失敗"
const SCOOPER_EQUIPMENT_UPGRADE_RESULT_TITLE := "升級結果"
const SCOOPER_EQUIPMENT_UPGRADE_GAINED_EXP := "EXP +%d"
const SCOOPER_EQUIPMENT_UPGRADE_LEVEL_UP := "裝備升級"
const SCOOPER_EQUIPMENT_UPGRADE_BROKEN := "裝備損壞"
const SCOOPER_EQUIPMENT_UPGRADE_SICK := "有貓咪生病了"
const SCOOPER_EQUIPMENT_UNLOCK_CONFIRM_TITLE := "解鎖裝備"
const SCOOPER_EQUIPMENT_UNLOCK_CONFIRM_BODY := "是否花費 %d 金幣解鎖 %s？"
const SCOOPER_EQUIPMENT_REFRESH_FAILED := "裝備資料刷新失敗"
const SCOOPER_EQUIPMENT_REFRESH_FAILED_DEFAULT := "無法更新裝備資料"
const SCOOPER_EQUIPMENT_BONUS_ALL := "全隊"
const SCOOPER_EQUIPMENT_BONUS_PER_LEVEL := "%s %s 每級 +%.1f%%"
const SCOOPER_EQUIPMENT_BONUS_TOTAL := "%s %s +%.1f%%"
const SCOOPER_EQUIPMENT_UPGRADE_DISABLED_GOLD := "金幣不足"
const SCOOPER_EQUIPMENT_LEVEL_UP_HINT := "請提升鏟屎官等級。"
const SCOOPER_MEMORY_UNLOCKED_SUMMARY := "已解鎖 %d/%d"

# Scooper ability labels
const SCOOPER_ABILITY_SUMMARY_FORMAT := "已擁有 %d"
const SCOOPER_ABILITY_EMPTY := "目前沒有特殊能力"
const SCOOPER_ABILITY_SOURCE_TITLE := "來源"
const SCOOPER_ABILITY_DESCRIPTION_TITLE := "效果"
const SCOOPER_ABILITY_SOURCE_VALUE := "取得方式：活動 成就 商店禮包"

# Scooper memory labels
const SCOOPER_MEMORY_SUMMARY_FORMAT := "回憶碎片：%d    已解鎖：%d / %d"
const SCOOPER_MEMORY_EMPTY := "目前沒有可顯示的回憶"
const SCOOPER_MEMORY_UNLOCKED := "已解鎖"
const SCOOPER_MEMORY_LOCKED := "未解鎖"
const SCOOPER_MEMORY_LOCKED_MASK := "未解鎖"
const SCOOPER_MEMORY_DETAIL := "查看詳情"
const SCOOPER_MEMORY_UNLOCKED_BUTTON := "已解鎖"
const SCOOPER_MEMORY_UNLOCK_BUTTON := "解鎖 %d/%d"
const SCOOPER_MEMORY_UNLOCK_NEED := "解鎖 %d/%d"
const SCOOPER_MEMORY_BONUS_PREFIX := "加成：%s"
const SCOOPER_MEMORY_COST_FORMAT := "解鎖消耗：%d 回憶碎片"
const SCOOPER_MEMORY_STATE_FORMAT := "狀態：%s"
const SCOOPER_MEMORY_CONFIRM_TITLE := "解鎖回憶"
const SCOOPER_MEMORY_CONFIRM_BODY := "是否消耗 %d 回憶碎片解鎖 %s？\n\n%s"
const SCOOPER_MEMORY_CONFIRM_FAILED := "解鎖失敗"
const SCOOPER_MEMORY_CONFIRM_FAILED_DEFAULT := "無法解鎖回憶"
const SCOOPER_MEMORY_CONFIRM_SUCCESS := "解鎖成功"
const SCOOPER_MEMORY_REFRESH_FAILED := "回憶資料刷新失敗"
const SCOOPER_MEMORY_REFRESH_FAILED_DEFAULT := "無法更新回憶資料"

# Scooper treasure labels
const SCOOPER_TREASURE_SUMMARY_FORMAT := "寶藏種類：%d    持有總數：%d"
const SCOOPER_TREASURE_EMPTY := "目前沒有持有的寶藏"
const SCOOPER_TREASURE_OBTAINED_AT := "最近取得：%s"
const SCOOPER_TREASURE_TOTAL_BONUS := "顯示加成屬性"
const SCOOPER_TREASURE_TOTAL_BONUS_TITLE := "全部加成屬性"

# Scooper achievement labels
const SCOOPER_ACHIEVEMENT_SUMMARY_FORMAT := "可領取：%d"
const SCOOPER_ACHIEVEMENT_SECTION_CLAIMED := "已領取"
const SCOOPER_ACHIEVEMENT_SECTION_ACTIVE := "進行中"
const SCOOPER_ACHIEVEMENT_CLAIM_ALL := "全部領取"
const SCOOPER_ACHIEVEMENT_EMPTY_ACTIVE := "目前沒有進行中的成就"
const SCOOPER_ACHIEVEMENT_EMPTY_CLAIMED := "目前沒有已領取的成就"
const SCOOPER_ACHIEVEMENT_COLLAPSE := "收合"
const SCOOPER_ACHIEVEMENT_EXPAND := "展開"
const SCOOPER_ACHIEVEMENT_COLLAPSED_HINT := "已領取成就已收合，需要時再展開查看。"
const SCOOPER_ACHIEVEMENT_REWARD_PREFIX := "獎勵：%s"
const SCOOPER_ACHIEVEMENT_COMPLETED_AT := "完成時間：%s"
const SCOOPER_ACHIEVEMENT_CLAIMED_AT := "領取時間：%s"
const SCOOPER_ACHIEVEMENT_ACTION_CLAIM := "領取獎勵"
const SCOOPER_ACHIEVEMENT_ACTION_CLAIMED := "已領取"
const SCOOPER_ACHIEVEMENT_ACTION_PENDING := "尚未完成"
const SCOOPER_ACHIEVEMENT_STATE_CLAIMED := "已領取"
const SCOOPER_ACHIEVEMENT_STATE_COMPLETED := "已完成"
const SCOOPER_ACHIEVEMENT_STATE_PENDING := "進行中"
const SCOOPER_ACHIEVEMENT_CLAIM_FAILED := "領取失敗"
const SCOOPER_ACHIEVEMENT_CLAIM_FAILED_DEFAULT := "無法領取成就獎勵"
const SCOOPER_ACHIEVEMENT_CLAIM_SUCCESS := "領取成功"
const SCOOPER_ACHIEVEMENT_CLAIM_EMPTY := "沒有額外獎勵資訊"
const SCOOPER_ACHIEVEMENT_REFRESH_FAILED := "成就資料刷新失敗"
const SCOOPER_ACHIEVEMENT_REFRESH_FAILED_DEFAULT := "無法更新成就資料"
